### ISSUE TITLE
Clashy_0.1.12_amd64.deb 在Debian 10.2 下，安装包依赖性错误

### ISSUE THREAD

**Issue by atzlinux** [SpongeNobody/Clashy#21]
clashy : 依赖: gir1.2-gnomekeyring-1.0 但无法安装它

使用 dpkg -i 命令可以强制安装，可以启动。

Debian 10.2 下有 gnome-keyring 这个包：

Package: gnome-keyring
Version: 3.28.2-5
Priority: optional
Section: gnome
Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Installed-Size: 4,859 kB
Depends: dconf-gsettings-backend | gsettings-backend, libc6 (>= 2.14), libcap-ng0 (>= 0.7.9), libgck-1-0 (>= 3.3.90), libgcr-base-3-1 (>= 3.28.0), libgcrypt20 (>= 1.8.0), libglib2.0-0 (>= 2.43.2), gcr (>= 3.4), default-dbus-session-bus | dbus-session-bus, p11-kit (>= 0.16), libcap2-bin, pinentry-gnome3
Recommends: libpam-gnome-keyring, gnome-keyring-pkcs11
Breaks: gnome-session (<< 3.20.0)
Homepage: https://wiki.gnome.org/GnomeKeyring
Tag: implemented-in::c, interface::daemon, interface::graphical,
 interface::x11, role::plugin, role::program, security::authentication,
 security::cryptography, security::privacy, suite::gnome,
 uitoolkit::gtk, use::storing, x11::application

Description: GNOME keyring services (daemon and tools)
 gnome-keyring is a daemon in the session, similar to ssh-agent,
 and other applications can use it to store passwords and other
 sensitive information.
 .
 The program can manage several keyrings, each with its own master
 password, and there is also a session keyring which is never stored to
 disk, but forgotten when the session ends.

不知道是否是这个软件包所需要的依赖包？

**Comment by Juansheng** [comment]
gir1.2-gnomekeyring-1.0 在 Debian busty 中被移除了。请参考类似 issue：[https://github.com/IsmaelMartinez/teams-for-linux/issues/208](url)

**Comment by kZime** [comment]
> gir1.2-gnomekeyring-1.0 在 Debian busty 中被移除了。请参考类似 issue：[https://github.com/IsmaelMartinez/teams-for-linux/issues/208](url)

类似issue: https://github.com/Foundry376/Mailspring/issues/998
通过
```sh
# dpkg --ignore-depends=gir1.2-gnomekeyring-1.0 -i Clashy_0.1.16_amd64.deb 
```
安装成功。

**Comment by atzlinux** [comment]
Clashy_0.1.21_amd64.deb 可以在 Debian 10.7.0 安装，没有依赖性问题，这个 issue 可以关闭了
