### ISSUE TITLE
Windows 10 ARM or x86 support

### ISSUE THREAD

**Issue by R0yl** [SpongeNobody/Clashy#25]
hi, love that i found an alternative gui for Clash. 

Any chance you may add Windows 10 ARM for several newest ARM laptops, or maybe x86 support.

THX

**Comment by SpongeNobody** [comment]
I will do some research about Electron on Windows ARM first. Maybe this is doable but I don't think my packaging CI supports Windows ARM and I don't have such a device 😂.

No guarantee when this will be done😞

**Comment by SpongeNobody** [comment]
Closing this issue for now and will re-open it when I got some clue about it.
