### ISSUE TITLE
Mac打不开

### ISSUE THREAD

**Issue by wyxpr** [SpongeNobody/Clashy#26]
<img width="418" alt="截屏2020-03-11上午7 31 33" src="https://user-images.githubusercontent.com/45851562/76368192-58757f80-636a-11ea-821f-01a14219b508.png">
Mac实测打不开

**Comment by SpongeNobody** [comment]
* Please add the following information:
    * Clashy version
    * OS version

* Check the downloaded file is corrupted or not. (Extracted `.app` file should be about 160MB)
* Check your security policy in your system preferences.

**Comment by Dcell** [comment]
Mac OS 10.15.5
Clashy version 1.16
Can not open.
security policy is 'allow all source'
