### ISSUE TITLE
Ubuntu 19.10 相关依赖缺失导致无法安装

### ISSUE THREAD

**Issue by jimlee2002** [SpongeNobody/Clashy#32]
安装时出错
```
$ sudo dpkg -i  Clashy_0.1.13_amd64.deb 
正在选中未选择的软件包 clashy。
(正在读取数据库 ... 系统当前共安装有 209297 个文件和目录。)
准备解压 Clashy_0.1.13_amd64.deb  ...
正在解压 clashy (0.1.13-80) ...
dpkg: 依赖关系问题使得 clashy 的配置工作不能继续：
 clashy 依赖于 gir1.2-gnomekeyring-1.0；然而：
  未安装软件包 gir1.2-gnomekeyring-1.0。

dpkg: 处理软件包 clashy (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 gnome-menus (3.32.0-1ubuntu1) 的触发器 ...
正在处理用于 desktop-file-utils (0.24-1ubuntu1) 的触发器 ...
正在处理用于 mime-support (3.63ubuntu1) 的触发器 ...
在处理时有错误发生：
 clashy
```
输入``sudo apt-get -install``，直接就提示卸载了
```
$ sudo apt -f install
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
正在修复依赖关系... 完成
下列软件包将被【卸载】：
  clashy
升级了 0 个软件包，新安装了 0 个软件包，要卸载 1 个软件包，有 0 个软件包未被升级。
有 1 个软件包没有被完全安装或卸载。
解压缩后将会空出 182 MB 的空间。
您希望继续执行吗？ [Y/n] n
中止。
```
尝试手动安装缺失的依赖，提示无安装候选
```
$ sudo apt install gir1.2-gnomekeyring-1.0
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
没有可用的软件包 gir1.2-gnomekeyring-1.0，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

E: 软件包 gir1.2-gnomekeyring-1.0 没有可安装候选
```
官方源、阿里云源都已经尝试过，都装不上

**Comment by alphazhao** [comment]
Ubuntu 20.04 LTS has the same failure.

> 安装时出错
> 
> ```
> $ sudo dpkg -i  Clashy_0.1.13_amd64.deb 
> 正在选中未选择的软件包 clashy。
> (正在读取数据库 ... 系统当前共安装有 209297 个文件和目录。)
> 准备解压 Clashy_0.1.13_amd64.deb  ...
> 正在解压 clashy (0.1.13-80) ...
> dpkg: 依赖关系问题使得 clashy 的配置工作不能继续：
>  clashy 依赖于 gir1.2-gnomekeyring-1.0；然而：
>   未安装软件包 gir1.2-gnomekeyring-1.0。
> 
> dpkg: 处理软件包 clashy (--install)时出错：
>  依赖关系问题 - 仍未被配置
> 正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
> 正在处理用于 gnome-menus (3.32.0-1ubuntu1) 的触发器 ...
> 正在处理用于 desktop-file-utils (0.24-1ubuntu1) 的触发器 ...
> 正在处理用于 mime-support (3.63ubuntu1) 的触发器 ...
> 在处理时有错误发生：
>  clashy
> ```
> 
> 输入`sudo apt-get -install`，直接就提示卸载了
> 
> ```
> $ sudo apt -f install
> 正在读取软件包列表... 完成
> 正在分析软件包的依赖关系树       
> 正在读取状态信息... 完成       
> 正在修复依赖关系... 完成
> 下列软件包将被【卸载】：
>   clashy
> 升级了 0 个软件包，新安装了 0 个软件包，要卸载 1 个软件包，有 0 个软件包未被升级。
> 有 1 个软件包没有被完全安装或卸载。
> 解压缩后将会空出 182 MB 的空间。
> 您希望继续执行吗？ [Y/n] n
> 中止。
> ```
> 
> 尝试手动安装缺失的依赖，提示无安装候选
> 
> ```
> $ sudo apt install gir1.2-gnomekeyring-1.0
> 正在读取软件包列表... 完成
> 正在分析软件包的依赖关系树       
> 正在读取状态信息... 完成       
> 没有可用的软件包 gir1.2-gnomekeyring-1.0，但是它被其它的软件包引用了。
> 这可能意味着这个缺失的软件包可能已被废弃，
> 或者只能在其他发布源中找到
> 
> E: 软件包 gir1.2-gnomekeyring-1.0 没有可安装候选
> ```
> 
> 官方源、阿里云源都已经尝试过，都装不上

**Comment by super5hunz1** [comment]
sudo apt-get install aptitude
vim /etc/apt/sources.list
+deb http://cz.archive.ubuntu.com/ubuntu bionic main universe

sudo aptitude update
sudo aptitude install gir1.2-gnomekeyring-1.0
dpkg -i Clash*.deb
