### ISSUE TITLE
希望可以支持 ubuntu 20.04

### ISSUE THREAD

**Issue by ydsjqt** [SpongeNobody/Clashy#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SpongeNobody** [comment]
Please leave a more detailed description. Such as issues you've met in Ubuntu 20.04. 

Closing this issue for now. Re-open it when provided more information.

Thanks.

**Comment by zylhub** [comment]
#32
