### ISSUE TITLE
Would it be possible to add support for Trojan? 

### ISSUE THREAD

**Issue by Eralien** [SpongeNobody/Clashy#38]
Hi, I am currently subscribing several Trojan service. Latest clash GUIs like clash for win and clashX has already add support for Trojan nodes. I love Clashy for its adaptivity and awesome UI.

Thank you for your contribution!

**Comment by SpongeNobody** [comment]
I might need some help with valid trojan configurations. Due to currently I don't have any provider offers trojan subscription.

**Comment by SpongeNobody** [comment]
Resolved in v0.1.15.
