### ISSUE TITLE
Do not support SSR subscription links!

### ISSUE THREAD

**Issue by xuyown** [SpongeNobody/Clashy#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Dear author, thank you very much for developing and maintaining Clashy. After upgrading to 0.1.15 and 0.1.16, I found that I do not support SSR subscription links.Since my subscription is only SSR, I hope clashy can continue to support SSR.

**Screenshots**
Proxy 0:Unsupport proxy type:ssr.
![深度截图_选择区域_20200507214252](https://user-images.githubusercontent.com/50038846/81302576-230cba00-90ad-11ea-8cb2-10f7b67257ae.png)

**Environment (please complete the following information):**
 - OS: [Linux]
 - OS version: [ubuntu 18.04]
 - Distribution (if needed): [Ubuntu ]
 - Clashy Version [0.1.15 and 0.1.16]

**Additional context**

**Comment by SpongeNobody** [comment]
Clashy use `Clash` as backend which doesn't support SSR protocol.

I could make a different client which uses `ClashR` backend but I can't guarantee when it will be done. So use clients with `ClashR` backend to get SSR support for now. 

I'll ping you on this ticket when it's ready.

Thanks.

**Comment by xuyown** [comment]
Thank you. Wish you all the best.
