### ISSUE TITLE
Please Support PAC

### ISSUE THREAD

**Issue by caryyu** [SpongeNobody/Clashy#42]
Is there any way that i can use this client to automatically generate PAC file instead of using manual setup in OS network, because this will cause all the traffic flow into Clashy with an unnecessary pace, basically the problem will be:

- All traffic going to Clashy first - `I don't like this`
- Only proxied traffic going to Clashy with a PAC file - `I like this`

**Comment by aobatu** [comment]
+1

**Comment by SpongeNobody** [comment]
All traffic going through Clashy doesn't mean those packets are going through your service provider as long as you are not using the "GLOBAL" mode. 

Also, the `Clash` configuration file is good enough for most cases and is a good solid replacement for PAC rules. See [this issue](https://github.com/Dreamacro/clash/issues/230) for more detail.

There is no plan in `Clashy` to support "PAC" files unless `Clashy`'s upstream `Clash` add support for it. 

For your case, I recommend you **not** to set `Clashy` **as system proxy** and use browser plugins like `SwitchyOmega`( available for both chrome and firefox ) along with `Clashy`.
