### ISSUE TITLE
Hi would you tell me what's wrong with my electron when building Clashy with VsCode?

### ISSUE THREAD

**Issue by iCanhua** [SpongeNobody/Clashy#45]
Skip checkForUpdatesAndNotify because application is not packed
(node:519) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:2390
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
(node:519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:519) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:2390
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
(node:519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by SpongeNobody** [comment]
Seems like clash core is not  running.
* Run `node pre-build.js` to download clash core binary for **current** platform.

Error `Skip checkForUpdatesAndNotify because application is not packed` can be ignored since it's logged by auto-update.

**Comment by iCanhua** [comment]
oh thank you  , I am very happy to get your response , but i met another problem, As you can see below the picture , while building over VsCode , I get nothing but an empty electron windows ,would you give me some advise to running it up ? your  repository will help me much
![empty](https://user-images.githubusercontent.com/10572998/83780388-af67c800-a6bf-11ea-9ff8-7783bb82b9dc.jpg)

**Comment by SpongeNobody** [comment]
Fire up another terminal & navigate to your Clashy source folder & run `yarn start` to start the webpage dev server.

I think I've put building phases in the README file 😉.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/50865553/83830504-ebc71280-a717-11ea-92dd-a7f7b1be0c16.png">

Close this issue for now. Feel free to ping me on this issue if you've met more problems.
