### ISSUE TITLE
I made a archlinux package

### ISSUE THREAD

**Issue by Arch-Jason** [SpongeNobody/Clashy#48]
I used debtap to chang the deb file to pacman file.
I only changed the depend ("gir1.2-gnomekeyring-1.0" to "gnome-keyring")
It works very well.
The file link ==(only can be download 1 time)== :
https://send.firefox.com/download/bc12ba06473d84e3/#LVXwUqhURTs8V-WPg2-udA

Please add this package into the releases, thank you!

**Comment by SpongeNobody** [comment]
Wow. Cool. Thanks for your contribution!

**Comment by SpongeNobody** [comment]
Added to the latest release page.

Thanks again.

**Comment by Arch-Jason** [comment]
> Added to the latest release page.
> 
> Thanks again.

Wow, thank you so much.

**Comment by Arch-Jason** [comment]
Oh no! I noticed you replyme just now. Sorry for my negligence. I used debtap to convert it and I didn't check the final package. 
I noticed that someone made a archlinux packge and uploaded to AUR, so you can remove my terrible package from releases page....(╥_╥)

**Comment by Arch-Jason** [comment]
Oh no! I just knew your reply today. Sorry I was careless. I used debtap to convert it and I didn't check the final package.
I noticed that someone made a archlinux packge and uploaded to AUR, so you can remove my terrible package from releases page....(╥_╥)
本蒟蒻再次向各位道歉(。・_・。)
