### ISSUE TITLE
The SUID sandbox helper binary is not configured correctly

### ISSUE THREAD

**Issue by KingRayVilla7** [SpongeNobody/Clashy#55]
In Terminal:
kingrayvilla@kingrayvilla-PC:~$ clashy
[8185:0812/175933.613112:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Clashy/chrome-sandbox is owned by root and has mode 4755.
追踪与中断点陷阱

 - Distribution Deppin V20
 - Clashy Version v0.0.17 (installed from the .deb package)

I am not able to solve this problem.This version of Clashy works perfectly on my other PCs which uses Linux Mint.
Can you offer some help?
Thanks a lot.

**Comment by KingRayVilla7** [comment]
running clashy but nothing happens

**Comment by nino-James** [comment]
I solved this problem on other debian linux ,You can try it, hope it helps you.
vim  /usr/share/applications/clashy.desktop
change ```Exec=/opt/Clashy/clashy %U``   to 
```Exec=/opt/Clashy/clashy %U  --no-sandbox``
run ```/opt/Clashy/clashy --no-sandbox``` as no  root

Sorry for my bad english, hope you can understand

**Comment by KingRayVilla7** [comment]
It works!
Thanks a lot!
