### ISSUE TITLE
why i cant subscrtion this 

### ISSUE THREAD

**Issue by dawoodiran** [SpongeNobody/Clashy#62]
https://subcon.dlj.tf/sub?target=clash&url=vmess%3A%2F%2FeyJhZGQiOiJsbGFqdi5yZWJsZHAudGVjaCIsImFpZCI6IjY0IiwiaG9zdCI6IiIsImlkIjoiM2I1ZTI1OGUtOGM1ZS00NWQzLWI3ZDItMDJjOGY1ZmMwYmIyIiwibmV0Ijoid3MiLCJwYXRoIjoiLyIsInBvcnQiOiI0NDMiLCJwcyI6IkVsZWN0cm9uIFByb3h5IiwidGxzIjoidGxzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiJ9

**Comment by SpongeNobody** [comment]
Confirmed is a bug. Will fix it in the next release.

**Comment by SpongeNobody** [comment]
Clashy will try to use url as part of the local configuration file name. This url is too long for most OS which will cause an error.
