### ISSUE TITLE
用一会Proxies界面就loading，Status界面显示{}，只得退出重启Clashy

### ISSUE THREAD

**Issue by mxlcpu** [SpongeNobody/Clashy#63]
如果不退出重启Clashy，就会一至这样，翻不去了就

**Comment by SpongeNobody** [comment]
Caused by clash core (upstream repo) crash. Will release a new version with the latest clash core soon. Sorry about any inconvenience.

**Comment by SpongeNobody** [comment]
Try the latest version please. Close issue for now. Ping me on this issue if you met this problem again.

**Comment by WhitePuffer** [comment]
This problem still remains in version 0.1.19.

**Comment by TimHe95** [comment]
The problem still remains in version 0.1.21. 

Refer [#72 Periodically crash in Ubuntu 20.10](https://github.com/SpongeNobody/Clashy/issues/72)
