### ISSUE TITLE
Would you please write a introduction for linux？

### ISSUE THREAD

**Issue by parluo** [SpongeNobody/Clashy#67]
On deepin, after subscripting and updating the nodes in proxies, then setting as the system proxy and modifing the port manually, I still cound't connect the internet use the proxy.

**Is this a bug in Clashy or there any wrong of my operations?**

**Comment by SpongeNobody** [comment]
Set as system proxy might NOT working on Linux desktop environments.

You need to use a browser plugin such as "proxy omega" to connect local clash server.
