### ISSUE TITLE
[Feature Request] Add the support of TUN/TAP in Linux

### ISSUE THREAD

**Issue by dingwen07** [SpongeNobody/Clashy#75]
**Is your feature request related to a problem? Please describe.**
Some Linux desktop environments do not have good support for proxy servers, applications do not respect system proxy settings.

**Describe the solution you'd like**
Use TUN/TAP to route all traffic.

**Comment by SpongeNobody** [comment]
Clashy using `Clash` as the proxy core, this issue might belong to upstream project [Clash](https://github.com/Dreamacro/clash)
