### ISSUE TITLE
Does the global mode work properly on the windows?

### ISSUE THREAD

**Issue by candiceatwb** [SpongeNobody/Clashy#88]
I install Clashy0.2.1 on my windows, set the rule mode, the proxy worked normally, switched to the global mode, I couldn’t open Facebook and other web pages. view the local log, the access page prompts timeout.
Does anyone have the same problem？

**Comment by SpongeNobody** [comment]
Depends on your providers configuration. Normally it will work properly on windows, but if you get timeout log you should check your connections from your provider first.
